factory: form
name: ldap_roles_settings
props:
    action: context.form_action
    class: ajax
widgets:
- roles_dn:
    factory: field:label:error:text
    value: expr:context.model.attrs.roles_dn
    props:
        label: i18n:roles_container_dn
        required: i18n:roles_container_dn_required
- roles_scope:
    factory: field:label:select
    value: expr:context.model.attrs.roles_scope
    props:
        label: i18n:roles_search_scope
        vocabulary: expr:context.scope_vocab
- roles_query:
    factory: field:label:text
    value: expr:context.model.attrs.roles_query
    props:
        label: i18n:roles_search_query_filter
- roles_object_classes:
    factory: field:label:text
    value: expr:u', '.join(context.model.attrs.get('roles_object_classes', []))
    props:
        label: i18n:roles_object_classes
- roles_aliases_attrmap:
    factory: field:label:error:dict
    value: expr:context.roles_aliases_attrmap
    props:
        label: i18n:role_attribute_aliases
        required: i18n:role_attribute_aliases_required
        static: True
        key_label: i18n:reserved_key
        value_label: i18n:ldap_attr_name
- roles_form_attrmap:
    factory: field:label:dict
    value: expr:context.model.attrs.roles_form_attrmap
    props:
        label: i18n:role_form_attributes
        key_label: i18n:ldap_attr_name
        value_label: i18n:form_label
#- roles_relation:
#    factory: field:label:text
#    value: expr:context.model.attrs.roles_relation
#    props:
#        label: Role-member-relation
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: i18n:save